### ISSUE TITLE
Repository Maintenance Clean-Up CheckList

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/cornerstone#372]
This is part of a larger effort to provide a consistent developer/contributor experience across our repositories, as well as to automate maintenance efforts so we can focus on the important technical bits.

- [ ] Switch coverage to CodeCov
- [ ] Switch CI to CircleCI
- [ ] Add `semantic-release`
    - [ ] Add `husky` to help coerce good commit messages
    - [ ] Add `commitizen` to create "wizard" for commit messages
- [ ] Normalize `eslint` rules; maybe export as custom ruleset
- [ ] Refresh dev dependencies to resolve vulnerability warnings
- [ ] Add `all-contributors` to celebrate/acknowledge our contributors

Feel free to comment with any questions, thoughts, or suggestions.
